# Avoids introducing vulnerable dependencies to the main branch.

name: Dependency review
on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      # To write dependency submission
      contents: write
      # To write comment on PR
      pull-requests: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Required because Dependabot Alerts doesn't natively support Scala
      - uses: guardian/setup-scala@cc7b39e238d789370aa98fa5f07e609b6527657d # v1.1.0
      - uses: scalacenter/sbt-dependency-submission@768f9b6dc79b0f5f2d103a706681fa6e206b86bc # v3.2.0
      
      - uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          fail-on-severity: high
          comment-summary-in-pr: always
