# Avoids introducing vulnerable dependencies to the main branch.

name: Dependency review
on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      # To write dependency submission
      contents: write
      # To write comment on PR
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Required because Dependabot Alerts doesn't natively support Scala
      - uses: guardian/setup-scala@cc7b39e238d789370aa98fa5f07e609b6527657d # v1.1.0
      - uses: scalacenter/sbt-dependency-submission@f43202114d7522a4b233e052f82c2eea8d658134 # v3.2.1
      
      - uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          fail-on-severity: high
          comment-summary-in-pr: always
